# Generated by Django 3.2.9 on 2021-11-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20211128_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='password',
            field=models.CharField(default='zefef', max_length=200),
        ),
    ]
