# Generated by Django 3.2.9 on 2021-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusermodel',
            name='DOB',
            field=models.DateField(),
        ),
    ]
