# Generated by Django 3.2.9 on 2021-12-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_createusermodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusermodel',
            name='DOB',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
